server:
  port: 8080

spring:
  application:
    name: bgpack-backend
  
  web:
    cors:
      allowed-origins: "http://localhost:3000,http://127.0.0.1:3000"
      allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
      allowed-headers: "*"
      allow-credentials: true
  
  # Wyłącz MongoDB dla testów
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
      - org.springframework.boot.autoconfigure.data.mongo.MongoDataAutoConfiguration
      - org.springframework.boot.autoconfigure.data.mongo.MongoRepositoriesAutoConfiguration
      - org.springframework.boot.autoconfigure.data.mongo.MongoRepositoriesAutoConfiguration
  
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=1000,expireAfterWrite=1h

logging:
  level:
    com.bgpack: DEBUG
    org.springframework.security: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

bgg:
  api:
    base-url: "https://www.boardgamegeek.com/xmlapi"
    timeout: 60000
    rate-limit: 1.0  # requests per second (1 request per second)
    max-requests-per-hour: 3600  # 1 request per second * 60 minutes * 60 seconds
    circuit-breaker-threshold: 5  # consecutive failures before opening circuit
    circuit-breaker-timeout: 300  # seconds before trying again
